version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      N8N_HOST: nickbarban.duckdns.org
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://nickbarban.duckdns.org/
      NODE_ENV: production
      TZ: ${TZ}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      DB_SQLITE_VACUUM_ON_STARTUP: "true"
    ports: 
      - "127.0.0.1:5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
